# Generated by Django 2.2.4 on 2019-08-12 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('notification_token', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('app_version', models.CharField(blank=True, max_length=10, null=True)),
                ('user_settings', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Configuration')),
                ('buffer_days', models.IntegerField(default=45)),
                ('edit_buffer_days', models.IntegerField(default=3)),
                ('role', models.IntegerField(choices=[(1, 'TEACHER'), (2, 'TEST'), (3, 'DEMO')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('class_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_teacher_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_teacher_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('user_type', models.CharField(max_length=100)),
                ('action', models.IntegerField()),
                ('entry_table', models.CharField(max_length=100)),
                ('model_id', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadofDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('notification_token', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('app_version', models.CharField(blank=True, max_length=10, null=True)),
                ('user_settings', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Configuration')),
                ('buffer_days', models.IntegerField(default=45)),
                ('edit_buffer_days', models.IntegerField(default=3)),
                ('role', models.IntegerField(choices=[(1, 'USER'), (2, 'TEST'), (3, 'DEMO')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='head_of_department', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_headofdepartment_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_headofdepartment_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('notification_token', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('app_version', models.CharField(blank=True, max_length=10, null=True)),
                ('user_settings', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Configuration')),
                ('buffer_days', models.IntegerField(default=45)),
                ('edit_buffer_days', models.IntegerField(default=3)),
                ('role', models.IntegerField(choices=[(1, 'USER'), (2, 'TEST'), (3, 'DEMO')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('assigned_class', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinator', to='attendance.Class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='class_coordinator', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_classcoordinator_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users_classcoordinator_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
