# Generated by Django 2.2.4 on 2019-08-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_class', to='attendance.Department'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'id')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
